-- Migration 006: Create cars table for Cardle database
-- This table stores all available cars for the game

CREATE TABLE IF NOT EXISTS cars (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    make TEXT NOT NULL,
    model TEXT NOT NULL,
    body TEXT NOT NULL,
    origin TEXT NOT NULL,
    power TEXT NOT NULL
);

-- Insert all cars into the database
INSERT INTO cars (make, model, body, origin, power) VALUES
('Toyota', 'Corolla', 'Sedan', 'JPN', 'ICE'),
('Toyota', 'RAV4', 'SUV', 'JPN', 'HYB'),
('Toyota', 'Camry', 'Sedan', 'JPN', 'HYB'),
('Toyota', 'Prius', 'Hatchback', 'JPN', 'HYB'),
('Toyota', 'Highlander', 'SUV', 'JPN', 'HYB'),
('Toyota', 'C-HR', 'SUV', 'JPN', 'HYB'),
('Toyota', 'Yaris', 'Hatchback', 'JPN', 'ICE'),
('Toyota', 'Hilux', 'Pickup', 'JPN', 'ICE'),
('Toyota', 'Land Cruiser', 'SUV', 'JPN', 'ICE'),
('Honda', 'Civic', 'Sedan', 'JPN', 'ICE'),
('Honda', 'CR-V', 'SUV', 'JPN', 'HYB'),
('Honda', 'Accord', 'Sedan', 'JPN', 'HYB'),
('Honda', 'HR-V', 'SUV', 'JPN', 'ICE'),
('Honda', 'Pilot', 'SUV', 'JPN', 'ICE'),
('Honda', 'Fit', 'Hatchback', 'JPN', 'ICE'),
('Nissan', 'Sentra', 'Sedan', 'JPN', 'ICE'),
('Nissan', 'Rogue', 'SUV', 'JPN', 'ICE'),
('Nissan', 'Altima', 'Sedan', 'JPN', 'ICE'),
('Nissan', 'Pathfinder', 'SUV', 'JPN', 'ICE'),
('Nissan', 'Qashqai', 'SUV', 'JPN', 'ICE'),
('Nissan', 'Juke', 'SUV', 'JPN', 'ICE'),
('Nissan', 'Leaf', 'Hatchback', 'JPN', 'EV'),
('Nissan', 'GT-R', 'Coupe', 'JPN', 'ICE'),
('Mazda', 'Mazda3', 'Hatchback', 'JPN', 'ICE'),
('Mazda', 'CX-5', 'SUV', 'JPN', 'ICE'),
('Mazda', 'MX-5', 'Convertible', 'JPN', 'ICE'),
('Mazda', 'CX-9', 'SUV', 'JPN', 'ICE'),
('Mazda', 'CX-30', 'SUV', 'JPN', 'ICE'),
('Subaru', 'Outback', 'Wagon', 'JPN', 'ICE'),
('Subaru', 'Forester', 'SUV', 'JPN', 'ICE'),
('Subaru', 'Crosstrek', 'SUV', 'JPN', 'ICE'),
('Subaru', 'Impreza', 'Hatchback', 'JPN', 'ICE'),
('Subaru', 'WRX', 'Sedan', 'JPN', 'ICE'),
('Subaru', 'BRZ', 'Coupe', 'JPN', 'ICE'),
('Ford', 'F-150', 'Pickup', 'USA', 'ICE'),
('Ford', 'Explorer', 'SUV', 'USA', 'ICE'),
('Ford', 'Escape', 'SUV', 'USA', 'HYB'),
('Ford', 'Mustang', 'Coupe', 'USA', 'ICE'),
('Ford', 'Edge', 'SUV', 'USA', 'ICE'),
('Ford', 'Focus', 'Hatchback', 'USA', 'ICE'),
('Ford', 'Fiesta', 'Hatchback', 'USA', 'ICE'),
('Ford', 'Bronco', 'SUV', 'USA', 'ICE'),
('Ford', 'Ranger', 'Pickup', 'USA', 'ICE'),
('Chevrolet', 'Silverado', 'Pickup', 'USA', 'ICE'),
('Chevrolet', 'Equinox', 'SUV', 'USA', 'ICE'),
('Chevrolet', 'Malibu', 'Sedan', 'USA', 'ICE'),
('Chevrolet', 'Traverse', 'SUV', 'USA', 'ICE'),
('Chevrolet', 'Camaro', 'Coupe', 'USA', 'ICE'),
('Chevrolet', 'Tahoe', 'SUV', 'USA', 'ICE'),
('Chevrolet', 'Suburban', 'SUV', 'USA', 'ICE'),
('Chevrolet', 'Corvette', 'Coupe', 'USA', 'ICE'),
('Chevrolet', 'Blazer', 'SUV', 'USA', 'ICE'),
('GMC', 'Sierra', 'Pickup', 'USA', 'ICE'),
('GMC', 'Acadia', 'SUV', 'USA', 'ICE'),
('GMC', 'Terrain', 'SUV', 'USA', 'ICE'),
('GMC', 'Yukon', 'SUV', 'USA', 'ICE'),
('Tesla', 'Model 3', 'Sedan', 'USA', 'EV'),
('Tesla', 'Model Y', 'SUV', 'USA', 'EV'),
('Tesla', 'Model S', 'Sedan', 'USA', 'EV'),
('Tesla', 'Model X', 'SUV', 'USA', 'EV'),
('Jeep', 'Wrangler', 'SUV', 'USA', 'ICE'),
('Jeep', 'Grand Cherokee', 'SUV', 'USA', 'ICE'),
('Jeep', 'Cherokee', 'SUV', 'USA', 'ICE'),
('Jeep', 'Compass', 'SUV', 'USA', 'ICE'),
('Jeep', 'Renegade', 'SUV', 'USA', 'ICE'),
('Jeep', 'Gladiator', 'Pickup', 'USA', 'ICE'),
('Ram', '1500', 'Pickup', 'USA', 'ICE'),
('Ram', '2500', 'Pickup', 'USA', 'ICE'),
('Dodge', 'Charger', 'Sedan', 'USA', 'ICE'),
('Dodge', 'Challenger', 'Coupe', 'USA', 'ICE'),
('Dodge', 'Durango', 'SUV', 'USA', 'ICE'),
('BMW', '3 Series', 'Sedan', 'GER', 'ICE'),
('BMW', 'X3', 'SUV', 'GER', 'ICE'),
('BMW', 'X5', 'SUV', 'GER', 'ICE'),
('BMW', '5 Series', 'Sedan', 'GER', 'ICE'),
('BMW', 'X1', 'SUV', 'GER', 'ICE'),
('BMW', '4 Series', 'Coupe', 'GER', 'ICE'),
('BMW', 'i4', 'Sedan', 'GER', 'EV'),
('BMW', 'iX', 'SUV', 'GER', 'EV'),
('BMW', 'X7', 'SUV', 'GER', 'ICE'),
('Mercedes-Benz', 'C-Class', 'Sedan', 'GER', 'ICE'),
('Mercedes-Benz', 'GLC', 'SUV', 'GER', 'ICE'),
('Mercedes-Benz', 'E-Class', 'Sedan', 'GER', 'ICE'),
('Mercedes-Benz', 'GLE', 'SUV', 'GER', 'ICE'),
('Mercedes-Benz', 'A-Class', 'Hatchback', 'GER', 'ICE'),
('Mercedes-Benz', 'S-Class', 'Sedan', 'GER', 'ICE'),
('Mercedes-Benz', 'EQS', 'Sedan', 'GER', 'EV'),
('Mercedes-Benz', 'G-Class', 'SUV', 'GER', 'ICE'),
('Audi', 'A4', 'Sedan', 'GER', 'ICE'),
('Audi', 'Q5', 'SUV', 'GER', 'ICE'),
('Audi', 'A3', 'Hatchback', 'GER', 'ICE'),
('Audi', 'Q3', 'SUV', 'GER', 'ICE'),
('Audi', 'A6', 'Sedan', 'GER', 'ICE'),
('Audi', 'Q7', 'SUV', 'GER', 'ICE'),
('Audi', 'e-tron', 'SUV', 'GER', 'EV'),
('Audi', 'TT', 'Coupe', 'GER', 'ICE'),
('Volkswagen', 'Golf', 'Hatchback', 'GER', 'ICE'),
('Volkswagen', 'Tiguan', 'SUV', 'GER', 'ICE'),
('Volkswagen', 'Passat', 'Sedan', 'GER', 'ICE'),
('Volkswagen', 'Jetta', 'Sedan', 'GER', 'ICE'),
('Volkswagen', 'Atlas', 'SUV', 'GER', 'ICE'),
('Volkswagen', 'Polo', 'Hatchback', 'GER', 'ICE'),
('Volkswagen', 'T-Roc', 'SUV', 'GER', 'ICE'),
('Volkswagen', 'ID.4', 'SUV', 'GER', 'EV'),
('Porsche', '911', 'Coupe', 'GER', 'ICE'),
('Porsche', 'Cayenne', 'SUV', 'GER', 'ICE'),
('Porsche', 'Macan', 'SUV', 'GER', 'ICE'),
('Porsche', 'Panamera', 'Sedan', 'GER', 'ICE'),
('Porsche', 'Taycan', 'Sedan', 'GER', 'EV'),
('Hyundai', 'Elantra', 'Sedan', 'KOR', 'ICE'),
('Hyundai', 'Tucson', 'SUV', 'KOR', 'ICE'),
('Hyundai', 'Santa Fe', 'SUV', 'KOR', 'ICE'),
('Hyundai', 'Sonata', 'Sedan', 'KOR', 'ICE'),
('Hyundai', 'Kona', 'SUV', 'KOR', 'ICE'),
('Hyundai', 'Palisade', 'SUV', 'KOR', 'ICE'),
('Hyundai', 'Ioniq', 'Hatchback', 'KOR', 'EV'),
('Hyundai', 'Venue', 'SUV', 'KOR', 'ICE'),
('Kia', 'Forte', 'Sedan', 'KOR', 'ICE'),
('Kia', 'Sportage', 'SUV', 'KOR', 'ICE'),
('Kia', 'Sorento', 'SUV', 'KOR', 'ICE'),
('Kia', 'Optima', 'Sedan', 'KOR', 'ICE'),
('Kia', 'Soul', 'Hatchback', 'KOR', 'ICE'),
('Kia', 'Telluride', 'SUV', 'KOR', 'ICE'),
('Kia', 'Rio', 'Hatchback', 'KOR', 'ICE'),
('Kia', 'Niro', 'SUV', 'KOR', 'HYB'),
('Kia', 'EV6', 'SUV', 'KOR', 'EV'),
('Lexus', 'RX', 'SUV', 'JPN', 'HYB'),
('Lexus', 'ES', 'Sedan', 'JPN', 'HYB'),
('Lexus', 'NX', 'SUV', 'JPN', 'HYB'),
('Lexus', 'GX', 'SUV', 'JPN', 'ICE'),
('Lexus', 'IS', 'Sedan', 'JPN', 'ICE'),
('Genesis', 'G90', 'Sedan', 'KOR', 'ICE'),
('Genesis', 'GV70', 'SUV', 'KOR', 'ICE'),
('Genesis', 'G80', 'Sedan', 'KOR', 'ICE'),
('Infiniti', 'Q50', 'Sedan', 'JPN', 'ICE'),
('Infiniti', 'QX60', 'SUV', 'JPN', 'ICE'),
('Infiniti', 'QX80', 'SUV', 'JPN', 'ICE'),
('Acura', 'MDX', 'SUV', 'JPN', 'ICE'),
('Acura', 'RDX', 'SUV', 'JPN', 'ICE'),
('Acura', 'TLX', 'Sedan', 'JPN', 'ICE'),
('Cadillac', 'Escalade', 'SUV', 'USA', 'ICE'),
('Cadillac', 'XT5', 'SUV', 'USA', 'ICE'),
('Cadillac', 'CT5', 'Sedan', 'USA', 'ICE'),
('Lincoln', 'Navigator', 'SUV', 'USA', 'ICE'),
('Lincoln', 'Aviator', 'SUV', 'USA', 'ICE'),
('Peugeot', '208', 'Hatchback', 'FRA', 'ICE'),
('Peugeot', '3008', 'SUV', 'FRA', 'ICE'),
('Peugeot', '2008', 'SUV', 'FRA', 'ICE'),
('Peugeot', '308', 'Hatchback', 'FRA', 'ICE'),
('Peugeot', '5008', 'SUV', 'FRA', 'ICE'),
('Renault', 'Clio', 'Hatchback', 'FRA', 'ICE'),
('Renault', 'Captur', 'SUV', 'FRA', 'ICE'),
('Renault', 'Megane', 'Hatchback', 'FRA', 'ICE'),
('Renault', 'Kadjar', 'SUV', 'FRA', 'ICE'),
('Citroën', 'C3', 'Hatchback', 'FRA', 'ICE'),
('Citroën', 'C4', 'Hatchback', 'FRA', 'ICE'),
('Citroën', 'C5', 'SUV', 'FRA', 'ICE'),
('Dacia', 'Sandero', 'Hatchback', 'ROM', 'ICE'),
('Dacia', 'Duster', 'SUV', 'ROM', 'ICE'),
('Dacia', 'Logan', 'Sedan', 'ROM', 'ICE'),
('Skoda', 'Octavia', 'Sedan', 'CZE', 'ICE'),
('Skoda', 'Superb', 'Sedan', 'CZE', 'ICE'),
('Skoda', 'Kodiaq', 'SUV', 'CZE', 'ICE'),
('Skoda', 'Karoq', 'SUV', 'CZE', 'ICE'),
('Skoda', 'Fabia', 'Hatchback', 'CZE', 'ICE'),
('SEAT', 'Leon', 'Hatchback', 'ESP', 'ICE'),
('SEAT', 'Ateca', 'SUV', 'ESP', 'ICE'),
('SEAT', 'Ibiza', 'Hatchback', 'ESP', 'ICE'),
('SEAT', 'Arona', 'SUV', 'ESP', 'ICE'),
('Volvo', 'XC90', 'SUV', 'SWE', 'ICE'),
('Volvo', 'XC60', 'SUV', 'SWE', 'ICE'),
('Volvo', 'XC40', 'SUV', 'SWE', 'ICE'),
('Volvo', 'S90', 'Sedan', 'SWE', 'ICE'),
('Jaguar', 'F-Pace', 'SUV', 'GBR', 'ICE'),
('Jaguar', 'E-Pace', 'SUV', 'GBR', 'ICE'),
('Jaguar', 'XF', 'Sedan', 'GBR', 'ICE'),
('Jaguar', 'F-Type', 'Coupe', 'GBR', 'ICE'),
('Land Rover', 'Range Rover', 'SUV', 'GBR', 'ICE'),
('Land Rover', 'Discovery', 'SUV', 'GBR', 'ICE'),
('Land Rover', 'Evoque', 'SUV', 'GBR', 'ICE'),
('Land Rover', 'Defender', 'SUV', 'GBR', 'ICE'),
('Mini', 'Cooper', 'Hatchback', 'GBR', 'ICE'),
('Mini', 'Countryman', 'SUV', 'GBR', 'ICE'),
('Mini', 'Clubman', 'Wagon', 'GBR', 'ICE'),
('Alfa Romeo', 'Giulia', 'Sedan', 'ITA', 'ICE'),
('Alfa Romeo', 'Stelvio', 'SUV', 'ITA', 'ICE'),
('Fiat', '500', 'Hatchback', 'ITA', 'ICE'),
('Fiat', 'Panda', 'Hatchback', 'ITA', 'ICE'),
('Fiat', 'Tipo', 'Hatchback', 'ITA', 'ICE'),
('Ferrari', 'Roma', 'Coupe', 'ITA', 'ICE'),
('Ferrari', 'F8', 'Coupe', 'ITA', 'ICE'),
('Ferrari', 'SF90', 'Coupe', 'ITA', 'HYB'),
('Lamborghini', 'Huracán', 'Coupe', 'ITA', 'ICE'),
('Lamborghini', 'Aventador', 'Coupe', 'ITA', 'ICE'),
('Lamborghini', 'Urus', 'SUV', 'ITA', 'ICE'),
('Maserati', 'Ghibli', 'Sedan', 'ITA', 'ICE'),
('Maserati', 'Levante', 'SUV', 'ITA', 'ICE'),
('Maserati', 'Quattroporte', 'Sedan', 'ITA', 'ICE');
