-- Migration 007: Refresh cars table with UK-focused dataset (300+ models)
-- Clears existing data and repopulates with UK branding and powertrains

DELETE FROM cars;

INSERT INTO cars (make, model, body, origin, power) VALUES
-- Ford (UK staples)
('Ford','Fiesta','Hatchback','GBR','ICE'),
('Ford','Focus','Hatchback','GBR','ICE'),
('Ford','Puma','SUV','GBR','MHEV'),
('Ford','Kuga','SUV','GBR','PHEV'),
('Ford','Explorer','SUV','USA','PHEV'),
('Ford','Mustang Mach-E','SUV','USA','EV'),
('Ford','Mustang','Coupe','USA','ICE'),
('Ford','Ranger','Pickup','GBR','ICE'),
('Ford','Transit Custom','Van','GBR','ICE'),
('Ford','Transit Courier','Van','GBR','ICE'),
('Ford','Galaxy','MPV','GBR','ICE'),
('Ford','S-MAX','MPV','GBR','ICE'),
('Ford','Edge','SUV','USA','ICE'),
('Ford','EcoSport','SUV','IND','ICE'),
('Ford','Mondeo','Saloon','GBR','ICE'),
('Ford','Tourneo Connect','MPV','GBR','ICE'),
('Ford','Tourneo Courier','MPV','GBR','ICE'),
('Ford','Focus ST','Hatchback','GBR','ICE'),
('Ford','Fiesta ST','Hatchback','GBR','ICE'),
('Ford','Bronco','SUV','USA','ICE'),

-- Vauxhall / Opel
('Vauxhall','Corsa','Hatchback','GBR','ICE'),
('Vauxhall','Corsa Electric','Hatchback','GBR','EV'),
('Vauxhall','Astra','Hatchback','GBR','ICE'),
('Vauxhall','Astra Sports Tourer','Estate','GBR','ICE'),
('Vauxhall','Astra Plug-in Hybrid','Hatchback','GBR','PHEV'),
('Vauxhall','Mokka','SUV','GBR','ICE'),
('Vauxhall','Mokka Electric','SUV','GBR','EV'),
('Vauxhall','Grandland','SUV','GBR','ICE'),
('Vauxhall','Grandland Hybrid','SUV','GBR','PHEV'),
('Vauxhall','Crossland','SUV','GBR','ICE'),
('Vauxhall','Insignia','Hatchback','GBR','ICE'),
('Vauxhall','Combo Life','MPV','GBR','ICE'),
('Vauxhall','Vivaro Life','MPV','GBR','ICE'),
('Vauxhall','Movano','Van','GBR','ICE'),
('Vauxhall','Combo Electric','Van','GBR','EV'),
('Vauxhall','Vivaro Electric','Van','GBR','EV'),
('Vauxhall','Astra GSe','Hatchback','GBR','PHEV'),
('Vauxhall','Mokka GSe','SUV','GBR','EV'),
('Vauxhall','Corsa GSe','Hatchback','GBR','EV'),
('Opel','Karl','Hatchback','GER','ICE'),

-- Volkswagen Group (VW/Skoda/SEAT/Škoda/Cupra/Audi/Porsche)
('Volkswagen','Golf','Hatchback','GER','ICE'),
('Volkswagen','Golf GTE','Hatchback','GER','PHEV'),
('Volkswagen','Golf GTI','Hatchback','GER','ICE'),
('Volkswagen','Golf R','Hatchback','GER','ICE'),
('Volkswagen','Polo','Hatchback','GER','ICE'),
('Volkswagen','T-Roc','SUV','GER','ICE'),
('Volkswagen','T-Cross','SUV','GER','ICE'),
('Volkswagen','Taigo','SUV','GER','ICE'),
('Volkswagen','Tiguan','SUV','GER','ICE'),
('Volkswagen','Tiguan eHybrid','SUV','GER','PHEV'),
('Volkswagen','Touareg','SUV','GER','ICE'),
('Volkswagen','ID.3','Hatchback','GER','EV'),
('Volkswagen','ID.4','SUV','GER','EV'),
('Volkswagen','ID.5','SUV-Coupe','GER','EV'),
('Volkswagen','ID.7','Saloon','GER','EV'),
('Volkswagen','Passat Estate','Estate','GER','ICE'),
('Volkswagen','Arteon','Fastback','GER','ICE'),
('Volkswagen','Sharan','MPV','GER','ICE'),
('Volkswagen','Multivan','MPV','GER','PHEV'),
('Volkswagen','Transporter','Van','GER','ICE'),
('Volkswagen','Caddy','Van','GER','ICE'),
('Volkswagen','California','Camper','GER','ICE'),
('Volkswagen','ID. Buzz','MPV','GER','EV'),
('Volkswagen','Amarok','Pickup','GER','ICE'),

('Audi','A1 Sportback','Hatchback','GER','ICE'),
('Audi','A3 Sportback','Hatchback','GER','ICE'),
('Audi','A3 TFSI e','Hatchback','GER','PHEV'),
('Audi','A4 Saloon','Saloon','GER','ICE'),
('Audi','A4 Avant','Estate','GER','ICE'),
('Audi','A5 Sportback','Fastback','GER','ICE'),
('Audi','A6 Saloon','Saloon','GER','ICE'),
('Audi','A6 Avant','Estate','GER','ICE'),
('Audi','A6 TFSI e','Saloon','GER','PHEV'),
('Audi','A7 Sportback','Fastback','GER','ICE'),
('Audi','A8','Saloon','GER','ICE'),
('Audi','Q2','SUV','GER','ICE'),
('Audi','Q3','SUV','GER','ICE'),
('Audi','Q3 TFSI e','SUV','GER','PHEV'),
('Audi','Q4 e-tron','SUV','GER','EV'),
('Audi','Q4 Sportback e-tron','SUV-Coupe','GER','EV'),
('Audi','Q5','SUV','GER','ICE'),
('Audi','Q5 TFSI e','SUV','GER','PHEV'),
('Audi','Q7','SUV','GER','ICE'),
('Audi','Q7 TFSI e','SUV','GER','PHEV'),
('Audi','Q8','SUV','GER','ICE'),
('Audi','Q8 e-tron','SUV','GER','EV'),
('Audi','Q8 Sportback e-tron','SUV-Coupe','GER','EV'),
('Audi','TT Coupe','Coupe','GER','ICE'),
('Audi','R8','Coupe','GER','ICE'),

('Skoda','Fabia','Hatchback','CZE','ICE'),
('Skoda','Scala','Hatchback','CZE','ICE'),
('Skoda','Octavia Hatch','Hatchback','CZE','ICE'),
('Skoda','Octavia Estate','Estate','CZE','ICE'),
('Skoda','Octavia iV','Estate','CZE','PHEV'),
('Skoda','Superb Hatch','Hatchback','CZE','ICE'),
('Skoda','Superb Estate','Estate','CZE','ICE'),
('Skoda','Superb iV','Estate','CZE','PHEV'),
('Skoda','Kamiq','SUV','CZE','ICE'),
('Skoda','Karoq','SUV','CZE','ICE'),
('Skoda','Kodiaq','SUV','CZE','ICE'),
('Skoda','Enyaq iV','SUV','CZE','EV'),
('Skoda','Enyaq Coupe iV','SUV-Coupe','CZE','EV'),

('SEAT','Ibiza','Hatchback','ESP','ICE'),
('SEAT','Leon','Hatchback','ESP','ICE'),
('SEAT','Leon Estate','Estate','ESP','ICE'),
('SEAT','Leon e-HYBRID','Hatchback','ESP','PHEV'),
('SEAT','Ateca','SUV','ESP','ICE'),
('SEAT','Tarraco','SUV','ESP','ICE'),
('SEAT','Arona','SUV','ESP','ICE'),

('Cupra','Born','Hatchback','ESP','EV'),
('Cupra','Leon','Hatchback','ESP','ICE'),
('Cupra','Leon e-HYBRID','Hatchback','ESP','PHEV'),
('Cupra','Formentor','SUV-Coupe','ESP','ICE'),
('Cupra','Formentor e-HYBRID','SUV-Coupe','ESP','PHEV'),
('Cupra','Ateca','SUV','ESP','ICE'),
('Cupra','Tavascan','SUV','ESP','EV'),

('Porsche','911 Carrera','Coupe','GER','ICE'),
('Porsche','911 Turbo','Coupe','GER','ICE'),
('Porsche','718 Cayman','Coupe','GER','ICE'),
('Porsche','718 Boxster','Convertible','GER','ICE'),
('Porsche','Panamera','Fastback','GER','PHEV'),
('Porsche','Cayenne','SUV','GER','ICE'),
('Porsche','Cayenne E-Hybrid','SUV','GER','PHEV'),
('Porsche','Macan','SUV','GER','ICE'),
('Porsche','Taycan','Saloon','GER','EV'),
('Porsche','Taycan Cross Turismo','Estate','GER','EV'),

-- BMW / MINI
('BMW','1 Series','Hatchback','GER','ICE'),
('BMW','2 Series Coupe','Coupe','GER','ICE'),
('BMW','2 Series Active Tourer','MPV','GER','PHEV'),
('BMW','3 Series Saloon','Saloon','GER','ICE'),
('BMW','3 Series Touring','Estate','GER','ICE'),
('BMW','330e','Saloon','GER','PHEV'),
('BMW','4 Series Coupe','Coupe','GER','ICE'),
('BMW','4 Series Gran Coupe','Fastback','GER','ICE'),
('BMW','i4','Fastback','GER','EV'),
('BMW','5 Series Saloon','Saloon','GER','ICE'),
('BMW','5 Series Touring','Estate','GER','ICE'),
('BMW','530e','Saloon','GER','PHEV'),
('BMW','7 Series','Saloon','GER','ICE'),
('BMW','i7','Saloon','GER','EV'),
('BMW','X1','SUV','GER','ICE'),
('BMW','iX1','SUV','GER','EV'),
('BMW','X2','SUV-Coupe','GER','ICE'),
('BMW','X3','SUV','GER','ICE'),
('BMW','X3 xDrive30e','SUV','GER','PHEV'),
('BMW','iX3','SUV','CHN','EV'),
('BMW','X4','SUV-Coupe','GER','ICE'),
('BMW','X5','SUV','GER','ICE'),
('BMW','X5 xDrive50e','SUV','GER','PHEV'),
('BMW','X6','SUV-Coupe','GER','ICE'),
('BMW','X7','SUV','GER','ICE'),
('BMW','iX','SUV','GER','EV'),
('BMW','Z4','Roadster','GER','ICE'),

('MINI','3-Door Hatch','Hatchback','GBR','ICE'),
('MINI','5-Door Hatch','Hatchback','GBR','ICE'),
('MINI','Convertible','Convertible','GBR','ICE'),
('MINI','Clubman','Estate','GBR','ICE'),
('MINI','Countryman','SUV','GBR','ICE'),
('MINI','Countryman Plug-in Hybrid','SUV','GBR','PHEV'),
('MINI','Electric','Hatchback','GBR','EV'),
('MINI','Aceman','Crossover','GBR','EV'),

-- Mercedes-Benz
('Mercedes-Benz','A-Class Hatchback','Hatchback','GER','ICE'),
('Mercedes-Benz','A-Class Saloon','Saloon','GER','ICE'),
('Mercedes-Benz','A 250 e','Hatchback','GER','PHEV'),
('Mercedes-Benz','B-Class','MPV','GER','ICE'),
('Mercedes-Benz','CLA Coupe','Fastback','GER','ICE'),
('Mercedes-Benz','CLA Shooting Brake','Estate','GER','ICE'),
('Mercedes-Benz','C-Class Saloon','Saloon','GER','MHEV'),
('Mercedes-Benz','C-Class Estate','Estate','GER','MHEV'),
('Mercedes-Benz','C 300 e','Saloon','GER','PHEV'),
('Mercedes-Benz','E-Class Saloon','Saloon','GER','MHEV'),
('Mercedes-Benz','E-Class Estate','Estate','GER','MHEV'),
('Mercedes-Benz','E 300 e','Saloon','GER','PHEV'),
('Mercedes-Benz','S-Class','Saloon','GER','MHEV'),
('Mercedes-Benz','S 580 e','Saloon','GER','PHEV'),
('Mercedes-Benz','GLA','SUV','GER','MHEV'),
('Mercedes-Benz','GLB','SUV','GER','MHEV'),
('Mercedes-Benz','GLC','SUV','GER','MHEV'),
('Mercedes-Benz','GLC Coupe','SUV-Coupe','GER','MHEV'),
('Mercedes-Benz','GLE','SUV','GER','MHEV'),
('Mercedes-Benz','GLE Coupe','SUV-Coupe','GER','MHEV'),
('Mercedes-Benz','GLS','SUV','GER','MHEV'),
('Mercedes-Benz','EQB','SUV','GER','EV'),
('Mercedes-Benz','EQA','SUV','GER','EV'),
('Mercedes-Benz','EQC','SUV','GER','EV'),
('Mercedes-Benz','EQE Saloon','Saloon','GER','EV'),
('Mercedes-Benz','EQE SUV','SUV','GER','EV'),
('Mercedes-Benz','EQS Saloon','Saloon','GER','EV'),
('Mercedes-Benz','EQS SUV','SUV','GER','EV'),
('Mercedes-Benz','AMG GT 4-Door','Fastback','GER','ICE'),
('Mercedes-Benz','AMG SL','Convertible','GER','ICE'),

-- Stellantis other (Peugeot, Citroën, DS, Fiat, Jeep, Alfa Romeo)
('Peugeot','208','Hatchback','FRA','ICE'),
('Peugeot','e-208','Hatchback','FRA','EV'),
('Peugeot','2008','SUV','FRA','ICE'),
('Peugeot','e-2008','SUV','FRA','EV'),
('Peugeot','3008','SUV','FRA','ICE'),
('Peugeot','3008 Hybrid','SUV','FRA','PHEV'),
('Peugeot','308 Hatch','Hatchback','FRA','ICE'),
('Peugeot','308 SW','Estate','FRA','ICE'),
('Peugeot','308 Hybrid','Hatchback','FRA','PHEV'),
('Peugeot','5008','SUV','FRA','ICE'),
('Peugeot','408 Fastback','Fastback','FRA','ICE'),
('Peugeot','408 Hybrid','Fastback','FRA','PHEV'),

('Citroen','C3','Hatchback','FRA','ICE'),
('Citroen','C3 Aircross','SUV','FRA','ICE'),
('Citroen','C4','Hatchback','FRA','ICE'),
('Citroen','e-C4','Hatchback','FRA','EV'),
('Citroen','C5 Aircross','SUV','FRA','ICE'),
('Citroen','C5 Aircross Hybrid','SUV','FRA','PHEV'),
('Citroen','Berlingo','MPV','FRA','ICE'),
('Citroen','e-Berlingo','MPV','FRA','EV'),
('Citroen','Dispatch','Van','FRA','ICE'),
('Citroen','e-Dispatch','Van','FRA','EV'),

('DS Automobiles','DS 3','SUV','FRA','ICE'),
('DS Automobiles','DS 3 E-Tense','SUV','FRA','EV'),
('DS Automobiles','DS 4','Hatchback','FRA','ICE'),
('DS Automobiles','DS 4 E-Tense','Hatchback','FRA','PHEV'),
('DS Automobiles','DS 7','SUV','FRA','ICE'),
('DS Automobiles','DS 7 E-Tense','SUV','FRA','PHEV'),
('DS Automobiles','DS 9','Saloon','FRA','PHEV'),

('Fiat','500','Hatchback','ITA','ICE'),
('Fiat','500e','Hatchback','ITA','EV'),
('Fiat','500X','SUV','ITA','ICE'),
('Fiat','Panda','Hatchback','ITA','ICE'),
('Fiat','Tipo Hatchback','Hatchback','ITA','ICE'),
('Fiat','Tipo Station Wagon','Estate','ITA','ICE'),
('Fiat','Doblo','Van','ITA','ICE'),
('Fiat','e-Doblo','Van','ITA','EV'),
('Fiat','Scudo','Van','ITA','ICE'),
('Fiat','e-Scudo','Van','ITA','EV'),

('Jeep','Avenger','SUV','ITA','EV'),
('Jeep','Renegade','SUV','ITA','ICE'),
('Jeep','Renegade 4xe','SUV','ITA','PHEV'),
('Jeep','Compass','SUV','ITA','ICE'),
('Jeep','Compass 4xe','SUV','ITA','PHEV'),
('Jeep','Wrangler','SUV','USA','PHEV'),
('Jeep','Grand Cherokee','SUV','USA','ICE'),
('Jeep','Grand Cherokee 4xe','SUV','USA','PHEV'),

('Alfa Romeo','Giulia','Saloon','ITA','ICE'),
('Alfa Romeo','Stelvio','SUV','ITA','ICE'),
('Alfa Romeo','Tonale','SUV','ITA','PHEV'),
('Alfa Romeo','MiTo','Hatchback','ITA','ICE'),

-- Toyota / Lexus
('Toyota','Aygo X','Crossover','JPN','ICE'),
('Toyota','Yaris','Hatchback','JPN','HYB'),
('Toyota','Yaris Cross','SUV','JPN','HYB'),
('Toyota','Corolla Hatchback','Hatchback','JPN','HYB'),
('Toyota','Corolla Touring Sports','Estate','JPN','HYB'),
('Toyota','Corolla Saloon','Saloon','JPN','HYB'),
('Toyota','C-HR','SUV','JPN','HYB'),
('Toyota','RAV4','SUV','JPN','HYB'),
('Toyota','RAV4 Plug-in Hybrid','SUV','JPN','PHEV'),
('Toyota','Highlander','SUV','JPN','HYB'),
('Toyota','Prius Plug-in','Hatchback','JPN','PHEV'),
('Toyota','GR86','Coupe','JPN','ICE'),
('Toyota','GR Yaris','Hatchback','JPN','ICE'),
('Toyota','GR Supra','Coupe','JPN','ICE'),
('Toyota','Land Cruiser','SUV','JPN','ICE'),
('Toyota','Proace City','Van','FRA','ICE'),
('Toyota','Proace City Electric','Van','FRA','EV'),
('Toyota','Proace','Van','FRA','ICE'),
('Toyota','Proace Electric','Van','FRA','EV'),

('Lexus','UX','SUV','JPN','HYB'),
('Lexus','UX 300e','SUV','JPN','EV'),
('Lexus','NX','SUV','JPN','HYB'),
('Lexus','NX 450h+','SUV','JPN','PHEV'),
('Lexus','RX','SUV','JPN','HYB'),
('Lexus','RX 450h+','SUV','JPN','PHEV'),
('Lexus','ES','Saloon','JPN','HYB'),
('Lexus','IS','Saloon','JPN','ICE'),
('Lexus','LS','Saloon','JPN','HYB'),
('Lexus','LC','Coupe','JPN','HYB'),

-- Nissan
('Nissan','Micra','Hatchback','FRA','ICE'),
('Nissan','Leaf','Hatchback','JPN','EV'),
('Nissan','Juke','SUV','GBR','ICE'),
('Nissan','Qashqai','SUV','GBR','MHEV'),
('Nissan','Qashqai e-POWER','SUV','GBR','HYB'),
('Nissan','X-Trail','SUV','JPN','MHEV'),
('Nissan','X-Trail e-POWER','SUV','JPN','HYB'),
('Nissan','Ariya','SUV','JPN','EV'),
('Nissan','Navara','Pickup','THA','ICE'),

-- Hyundai / Kia
('Hyundai','i10','Hatchback','IND','ICE'),
('Hyundai','i20','Hatchback','TUR','ICE'),
('Hyundai','i20 N','Hatchback','TUR','ICE'),
('Hyundai','i30 Hatchback','Hatchback','CZE','ICE'),
('Hyundai','i30 Fastback','Fastback','CZE','ICE'),
('Hyundai','i30 N','Hatchback','CZE','ICE'),
('Hyundai','Kona','SUV','KOR','EV'),
('Hyundai','Kona Hybrid','SUV','KOR','HYB'),
('Hyundai','Tucson','SUV','KOR','ICE'),
('Hyundai','Tucson Hybrid','SUV','KOR','HYB'),
('Hyundai','Tucson Plug-in Hybrid','SUV','KOR','PHEV'),
('Hyundai','Santa Fe','SUV','USA','ICE'),
('Hyundai','Santa Fe Hybrid','SUV','USA','HYB'),
('Hyundai','Santa Fe Plug-in Hybrid','SUV','USA','PHEV'),
('Hyundai','Ioniq 5','SUV','KOR','EV'),
('Hyundai','Ioniq 6','Saloon','KOR','EV'),
('Hyundai','Staria','MPV','KOR','ICE'),

('Kia','Picanto','Hatchback','KOR','ICE'),
('Kia','Rio','Hatchback','MEX','ICE'),
('Kia','Ceed','Hatchback','SVK','ICE'),
('Kia','Ceed Sportswagon','Estate','SVK','ICE'),
('Kia','ProCeed','Shooting Brake','SVK','ICE'),
('Kia','XCeed','Crossover','SVK','PHEV'),
('Kia','Niro Hybrid','SUV','KOR','HYB'),
('Kia','Niro Plug-in Hybrid','SUV','KOR','PHEV'),
('Kia','Niro EV','SUV','KOR','EV'),
('Kia','Sportage','SUV','KOR','ICE'),
('Kia','Sportage Hybrid','SUV','KOR','HYB'),
('Kia','Sportage Plug-in Hybrid','SUV','KOR','PHEV'),
('Kia','Sorento','SUV','KOR','ICE'),
('Kia','Sorento Hybrid','SUV','KOR','HYB'),
('Kia','Sorento Plug-in Hybrid','SUV','KOR','PHEV'),
('Kia','EV6','Crossover','KOR','EV'),
('Kia','EV9','SUV','KOR','EV'),

-- Mazda / Honda / Subaru
('Mazda','Mazda2','Hatchback','JPN','ICE'),
('Mazda','Mazda2 Hybrid','Hatchback','JPN','HYB'),
('Mazda','Mazda3 Hatchback','Hatchback','JPN','ICE'),
('Mazda','Mazda3 Saloon','Saloon','JPN','ICE'),
('Mazda','CX-30','SUV','JPN','MHEV'),
('Mazda','CX-5','SUV','JPN','ICE'),
('Mazda','MX-30','SUV','JPN','EV'),
('Mazda','MX-5 Roadster','Convertible','JPN','ICE'),
('Mazda','MX-5 RF','Coupe','JPN','ICE'),
('Mazda','CX-60','SUV','JPN','PHEV'),

('Honda','Jazz','Hatchback','JPN','HYB'),
('Honda','Civic Hatchback','Hatchback','JPN','HYB'),
('Honda','Civic Type R','Hatchback','JPN','ICE'),
('Honda','HR-V','SUV','JPN','HYB'),
('Honda','ZR-V','SUV','JPN','HYB'),
('Honda','CR-V Hybrid','SUV','JPN','HYB'),
('Honda','CR-V Plug-in Hybrid','SUV','JPN','PHEV'),
('Honda','e','Hatchback','JPN','EV'),

('Subaru','Impreza','Hatchback','JPN','MHEV'),
('Subaru','XV','SUV','JPN','MHEV'),
('Subaru','Outback','Estate','JPN','MHEV'),
('Subaru','Forester','SUV','JPN','MHEV'),
('Subaru','Solterra','SUV','JPN','EV'),

-- Volvo / Polestar / Saab
('Volvo','XC40','SUV','SWE','MHEV'),
('Volvo','XC40 Recharge','SUV','SWE','EV'),
('Volvo','EX30','SUV','CHN','EV'),
('Volvo','EX90','SUV','SWE','EV'),
('Volvo','C40 Recharge','SUV-Coupe','SWE','EV'),
('Volvo','S60','Saloon','USA','MHEV'),
('Volvo','S90','Saloon','CHN','MHEV'),
('Volvo','V60','Estate','SWE','MHEV'),
('Volvo','V60 Recharge','Estate','SWE','PHEV'),
('Volvo','V90','Estate','SWE','MHEV'),
('Volvo','XC60','SUV','SWE','MHEV'),
('Volvo','XC60 Recharge','SUV','SWE','PHEV'),
('Volvo','XC90','SUV','SWE','MHEV'),
('Volvo','XC90 Recharge','SUV','SWE','PHEV'),
('Polestar','2','Fastback','CHN','EV'),
('Polestar','3','SUV','CHN','EV'),
('Polestar','4','SUV-Coupe','CHN','EV'),

-- Jaguar Land Rover
('Jaguar','XE','Saloon','GBR','MHEV'),
('Jaguar','XF','Saloon','GBR','MHEV'),
('Jaguar','F-Pace','SUV','GBR','MHEV'),
('Jaguar','E-Pace','SUV','GBR','MHEV'),
('Jaguar','I-Pace','SUV','GBR','EV'),
('Jaguar','F-Type Coupe','Coupe','GBR','ICE'),
('Jaguar','F-Type Convertible','Convertible','GBR','ICE'),

('Land Rover','Defender 90','SUV','GBR','MHEV'),
('Land Rover','Defender 110','SUV','GBR','MHEV'),
('Land Rover','Defender 130','SUV','GBR','MHEV'),
('Land Rover','Discovery Sport','SUV','GBR','MHEV'),
('Land Rover','Discovery','SUV','GBR','MHEV'),
('Land Rover','Range Rover Evoque','SUV','GBR','MHEV'),
('Land Rover','Range Rover Velar','SUV','GBR','MHEV'),
('Land Rover','Range Rover Sport','SUV','GBR','MHEV'),
('Land Rover','Range Rover Sport PHEV','SUV','GBR','PHEV'),
('Land Rover','Range Rover','SUV','GBR','MHEV'),
('Land Rover','Range Rover PHEV','SUV','GBR','PHEV'),

-- Tesla
('Tesla','Model 3','Saloon','USA','EV'),
('Tesla','Model Y','SUV','CHN','EV'),
('Tesla','Model S','Liftback','USA','EV'),
('Tesla','Model X','SUV','USA','EV'),

-- Renault / Dacia
('Renault','Clio','Hatchback','FRA','MHEV'),
('Renault','Captur','SUV','FRA','MHEV'),
('Renault','Captur E-Tech','SUV','FRA','PHEV'),
('Renault','Arkana','SUV-Coupe','FRA','MHEV'),
('Renault','Austral','SUV','ESP','MHEV'),
('Renault','Austral E-Tech','SUV','ESP','HYB'),
('Renault','Megane E-Tech Electric','Hatchback','FRA','EV'),
('Renault','Scenic E-Tech Electric','MPV','FRA','EV'),
('Renault','Zoe','Hatchback','FRA','EV'),
('Renault','Kangoo','Van','FRA','ICE'),
('Renault','Kangoo E-Tech','Van','FRA','EV'),

('Dacia','Sandero','Hatchback','ROM','ICE'),
('Dacia','Sandero Stepway','Crossover','ROM','ICE'),
('Dacia','Duster','SUV','ROM','ICE'),
('Dacia','Jogger','MPV','ROM','MHEV'),
('Dacia','Spring','Hatchback','CHN','EV'),

-- MG (UK market branding)
('MG','MG3','Hatchback','CHN','ICE'),
('MG','MG4 EV','Hatchback','CHN','EV'),
('MG','MG5 EV','Estate','CHN','EV'),
('MG','ZS','SUV','CHN','ICE'),
('MG','ZS EV','SUV','CHN','EV'),
('MG','HS','SUV','CHN','ICE'),
('MG','HS Plug-in Hybrid','SUV','CHN','PHEV'),
('MG','Marvel R','SUV','CHN','EV'),

-- Other notable UK-market models
('Suzuki','Swift','Hatchback','JPN','ICE'),
('Suzuki','Swift Sport','Hatchback','JPN','ICE'),
('Suzuki','Ignis','Crossover','JPN','MHEV'),
('Suzuki','Vitara','SUV','HUN','MHEV'),
('Suzuki','S-Cross','SUV','HUN','MHEV'),
('Suzuki','Across','SUV','JPN','PHEV'),
('Suzuki','Jimny LCV','Van','JPN','ICE'),

('Mitsubishi','Outlander PHEV','SUV','JPN','PHEV'),
('Mitsubishi','Eclipse Cross PHEV','SUV','JPN','PHEV'),
('Mitsubishi','ASX','SUV','ESP','MHEV'),
('Mitsubishi','L200','Pickup','THA','ICE'),

('Honda','e:Ny1','SUV','CHN','EV'),
('BYD','Atto 3','SUV','CHN','EV'),
('BYD','Dolphin','Hatchback','CHN','EV'),
('BYD','Seal','Saloon','CHN','EV'),
('ORA','Funky Cat','Hatchback','CHN','EV'),

('Peugeot','Traveller','MPV','FRA','ICE'),
('Toyota','Camry','Saloon','JPN','HYB'),
('Volkswagen','Up!','Hatchback','GER','ICE'),
('Volkswagen','ID.2all','Hatchback','GER','EV'),
('BMW','i5','Saloon','GER','EV'),
('BMW','i5 Touring','Estate','GER','EV'),
('Mercedes-Benz','GLC 300 e','SUV','GER','PHEV'),
('Kia','Ceed Plug-in Hybrid','Hatchback','SVK','PHEV'),
('Hyundai','Bayon','SUV','TUR','MHEV'),
('Hyundai','i10 N Line','Hatchback','IND','ICE'),
('Ford','Focus Estate','Estate','GBR','ICE'),
('Ford','Transit Custom Electric','Van','GBR','EV'),
('Renault','Traffic','Van','FRA','ICE'),
('Renault','Master E-Tech','Van','FRA','EV'),
('Mercedes-Benz','Vito','Van','ESP','ICE'),
('Mercedes-Benz','eVito','Van','GER','EV'),
('Peugeot','Boxer','Van','ITA','ICE'),
('Citroen','Relay','Van','ITA','ICE'),
('Vauxhall','Movano Electric','Van','GBR','EV'),
('Fiat','E-Ducato','Van','ITA','EV'),
('Nissan','Townstar','Van','FRA','ICE'),
('Nissan','Townstar Electric','Van','FRA','EV'),
('Toyota','Hilux','Pickup','THA','ICE'),
('Isuzu','D-Max','Pickup','THA','ICE'),
('SsangYong','Korando','SUV','KOR','ICE'),
('SsangYong','Rexton','SUV','KOR','ICE'),
('SsangYong','Musso','Pickup','KOR','ICE'),
('Tesla','Cybertruck (UK Spec)','Pickup','USA','EV');
